// minimal latency 3-sorter for B bits values
// generated by mlnsgenfastc2
// comparisons=3, total cases=8, orderings=6
module nsorter_3 #(
  parameter B = 64
) (
  input [B-1:0] i0,
  output reg [B-1:0] o0,
  input [B-1:0] i1,
  output reg [B-1:0] o1,
  input [B-1:0] i2,
  output reg [B-1:0] o2
);
  wire c0 = i0 < i1;
  wire c1 = i0 < i2;
  wire c2 = i1 < i2;
  wire [2:0] c = {c0,c1,c2};
  always @(*) begin
    casez (c)
      3'b11?: o0=i0; // 2 cases, 1 merged cases
      3'b0?1: o0=i1; // 2 cases, 1 merged cases
      3'b?00: o0=i2; // 2 cases, 1 merged cases
      default: o0={B{1'bx}}; // 2 unreachable cases
    endcase
  end
  always @(*) begin
    casez (c)
      3'b011, 3'b100: o1=i0; // 2 cases, 2 merged cases
      3'b000, 3'b111: o1=i1; // 2 cases, 2 merged cases
      3'b001, 3'b110: o1=i2; // 2 cases, 2 merged cases
      default: o1={B{1'bx}}; // 2 unreachable cases
    endcase
  end
  always @(*) begin
    casez (c)
      3'b00?: o2=i0; // 2 cases, 1 merged cases
      3'b1?0: o2=i1; // 2 cases, 1 merged cases
      3'b?11: o2=i2; // 2 cases, 1 merged cases
      default: o2={B{1'bx}}; // 2 unreachable cases
    endcase
  end
endmodule
