// minimal latency 2-sorter for B bits values
// generated by mlnsgenlarge
module nsorter_2_large #(
  parameter B = 64
) (
  input [B-1:0] i0,
  output reg [B-1:0] o0,
  input [B-1:0] i1,
  output reg [B-1:0] o1
);
  wire [0:0] r0 = (i0 > i1);
  wire [0:0] r1 = (i1 >= i0);
  always @(*) begin
    o0 = {B{1'bx}};
    o1 = {B{1'bx}};
    case (r0)
      0: o0 = i0;
      1: o1 = i0;
    endcase
    case (r1)
      0: o0 = i1;
      1: o1 = i1;
    endcase
  end
endmodule
