// minimal latency 3-sorter for B bits values
// generated by mlnsgenlarge
module nsorter_3_large #(
  parameter B = 64
) (
  input [B-1:0] i0,
  output reg [B-1:0] o0,
  input [B-1:0] i1,
  output reg [B-1:0] o1,
  input [B-1:0] i2,
  output reg [B-1:0] o2
);
  wire [1:0] r0 = (i0 > i1) + (i0 > i2);
  wire [1:0] r1 = (i1 >= i0) + (i1 > i2);
  wire [1:0] r2 = (i2 >= i0) + (i2 >= i1);
  always @(*) begin
    o0 = {B{1'bx}};
    o1 = {B{1'bx}};
    o2 = {B{1'bx}};
    case (r0)
      0: o0 = i0;
      1: o1 = i0;
      2: o2 = i0;
      default: ; // noop
    endcase
    case (r1)
      0: o0 = i1;
      1: o1 = i1;
      2: o2 = i1;
      default: ; // noop
    endcase
    case (r2)
      0: o0 = i2;
      1: o1 = i2;
      2: o2 = i2;
      default: ; // noop
    endcase
  end
endmodule
