// minimal latency 2-sorter for B bits values
// generated by mlnsgen
// comparisons=1, evals=3, total cases=2, valid cases=2, orderings=2
module nsorter_2 #(
  parameter B = 64
) (
  input [B-1:0] in0,
  output reg [B-1:0] out0,
  input [B-1:0] in1,
  output reg [B-1:0] out1
);
  wire c0 = in0 < in1;
  always @(*) begin
    case ({c0})
      1'b0: begin out0 = in1; out1 = in0; end
      1'b1: begin out0 = in0; out1 = in1; end
    endcase
  end
endmodule
