// minimal latency 9-sorter for B bits values
// generated by mlnsgenlarge
module nsorter_9_large #(
  parameter B = 64
) (
  input [B-1:0] i0,
  output reg [B-1:0] o0,
  input [B-1:0] i1,
  output reg [B-1:0] o1,
  input [B-1:0] i2,
  output reg [B-1:0] o2,
  input [B-1:0] i3,
  output reg [B-1:0] o3,
  input [B-1:0] i4,
  output reg [B-1:0] o4,
  input [B-1:0] i5,
  output reg [B-1:0] o5,
  input [B-1:0] i6,
  output reg [B-1:0] o6,
  input [B-1:0] i7,
  output reg [B-1:0] o7,
  input [B-1:0] i8,
  output reg [B-1:0] o8
);
  wire [3:0] r0 = (i0 > i1) + (i0 > i2) + (i0 > i3) + (i0 > i4) + (i0 > i5) + (i0 > i6) + (i0 > i7) + (i0 > i8);
  wire [3:0] r1 = (i1 >= i0) + (i1 > i2) + (i1 > i3) + (i1 > i4) + (i1 > i5) + (i1 > i6) + (i1 > i7) + (i1 > i8);
  wire [3:0] r2 = (i2 >= i0) + (i2 >= i1) + (i2 > i3) + (i2 > i4) + (i2 > i5) + (i2 > i6) + (i2 > i7) + (i2 > i8);
  wire [3:0] r3 = (i3 >= i0) + (i3 >= i1) + (i3 >= i2) + (i3 > i4) + (i3 > i5) + (i3 > i6) + (i3 > i7) + (i3 > i8);
  wire [3:0] r4 = (i4 >= i0) + (i4 >= i1) + (i4 >= i2) + (i4 >= i3) + (i4 > i5) + (i4 > i6) + (i4 > i7) + (i4 > i8);
  wire [3:0] r5 = (i5 >= i0) + (i5 >= i1) + (i5 >= i2) + (i5 >= i3) + (i5 >= i4) + (i5 > i6) + (i5 > i7) + (i5 > i8);
  wire [3:0] r6 = (i6 >= i0) + (i6 >= i1) + (i6 >= i2) + (i6 >= i3) + (i6 >= i4) + (i6 >= i5) + (i6 > i7) + (i6 > i8);
  wire [3:0] r7 = (i7 >= i0) + (i7 >= i1) + (i7 >= i2) + (i7 >= i3) + (i7 >= i4) + (i7 >= i5) + (i7 >= i6) + (i7 > i8);
  wire [3:0] r8 = (i8 >= i0) + (i8 >= i1) + (i8 >= i2) + (i8 >= i3) + (i8 >= i4) + (i8 >= i5) + (i8 >= i6) + (i8 >= i7);
  always @(*) begin
    o0 = {B{1'bx}};
    o1 = {B{1'bx}};
    o2 = {B{1'bx}};
    o3 = {B{1'bx}};
    o4 = {B{1'bx}};
    o5 = {B{1'bx}};
    o6 = {B{1'bx}};
    o7 = {B{1'bx}};
    o8 = {B{1'bx}};
    case (r0)
      0: o0 = i0;
      1: o1 = i0;
      2: o2 = i0;
      3: o3 = i0;
      4: o4 = i0;
      5: o5 = i0;
      6: o6 = i0;
      7: o7 = i0;
      8: o8 = i0;
      default: ; // noop
    endcase
    case (r1)
      0: o0 = i1;
      1: o1 = i1;
      2: o2 = i1;
      3: o3 = i1;
      4: o4 = i1;
      5: o5 = i1;
      6: o6 = i1;
      7: o7 = i1;
      8: o8 = i1;
      default: ; // noop
    endcase
    case (r2)
      0: o0 = i2;
      1: o1 = i2;
      2: o2 = i2;
      3: o3 = i2;
      4: o4 = i2;
      5: o5 = i2;
      6: o6 = i2;
      7: o7 = i2;
      8: o8 = i2;
      default: ; // noop
    endcase
    case (r3)
      0: o0 = i3;
      1: o1 = i3;
      2: o2 = i3;
      3: o3 = i3;
      4: o4 = i3;
      5: o5 = i3;
      6: o6 = i3;
      7: o7 = i3;
      8: o8 = i3;
      default: ; // noop
    endcase
    case (r4)
      0: o0 = i4;
      1: o1 = i4;
      2: o2 = i4;
      3: o3 = i4;
      4: o4 = i4;
      5: o5 = i4;
      6: o6 = i4;
      7: o7 = i4;
      8: o8 = i4;
      default: ; // noop
    endcase
    case (r5)
      0: o0 = i5;
      1: o1 = i5;
      2: o2 = i5;
      3: o3 = i5;
      4: o4 = i5;
      5: o5 = i5;
      6: o6 = i5;
      7: o7 = i5;
      8: o8 = i5;
      default: ; // noop
    endcase
    case (r6)
      0: o0 = i6;
      1: o1 = i6;
      2: o2 = i6;
      3: o3 = i6;
      4: o4 = i6;
      5: o5 = i6;
      6: o6 = i6;
      7: o7 = i6;
      8: o8 = i6;
      default: ; // noop
    endcase
    case (r7)
      0: o0 = i7;
      1: o1 = i7;
      2: o2 = i7;
      3: o3 = i7;
      4: o4 = i7;
      5: o5 = i7;
      6: o6 = i7;
      7: o7 = i7;
      8: o8 = i7;
      default: ; // noop
    endcase
    case (r8)
      0: o0 = i8;
      1: o1 = i8;
      2: o2 = i8;
      3: o3 = i8;
      4: o4 = i8;
      5: o5 = i8;
      6: o6 = i8;
      7: o7 = i8;
      8: o8 = i8;
      default: ; // noop
    endcase
  end
endmodule
