// minimal latency 2-sorter for B bits values
// generated by mlnsgenfast
// comparisons=1, total cases=2, orderings=2
module nsorter_2 #(
  parameter B = 64
) (
  input [B-1:0] i0,
  output reg [B-1:0] o0,
  input [B-1:0] i1,
  output reg [B-1:0] o1
);
  wire c0 = (i0 < i1);
  always @(*) begin
    case ({c0})
      1'b1: begin o0=i0; o1=i1; end
      1'b0: begin o0=i1; o1=i0; end
    endcase
  end
endmodule
