// minimal latency 6-sorter for B bits values
// generated by mlnsgenlarge
module nsorter_6_large #(
  parameter B = 64
) (
  input [B-1:0] i0,
  output reg [B-1:0] o0,
  input [B-1:0] i1,
  output reg [B-1:0] o1,
  input [B-1:0] i2,
  output reg [B-1:0] o2,
  input [B-1:0] i3,
  output reg [B-1:0] o3,
  input [B-1:0] i4,
  output reg [B-1:0] o4,
  input [B-1:0] i5,
  output reg [B-1:0] o5
);
  wire [2:0] r0 = (i0 > i1) + (i0 > i2) + (i0 > i3) + (i0 > i4) + (i0 > i5);
  wire [2:0] r1 = (i1 >= i0) + (i1 > i2) + (i1 > i3) + (i1 > i4) + (i1 > i5);
  wire [2:0] r2 = (i2 >= i0) + (i2 >= i1) + (i2 > i3) + (i2 > i4) + (i2 > i5);
  wire [2:0] r3 = (i3 >= i0) + (i3 >= i1) + (i3 >= i2) + (i3 > i4) + (i3 > i5);
  wire [2:0] r4 = (i4 >= i0) + (i4 >= i1) + (i4 >= i2) + (i4 >= i3) + (i4 > i5);
  wire [2:0] r5 = (i5 >= i0) + (i5 >= i1) + (i5 >= i2) + (i5 >= i3) + (i5 >= i4);
  always @(*) begin
    o0 = {B{1'bx}};
    o1 = {B{1'bx}};
    o2 = {B{1'bx}};
    o3 = {B{1'bx}};
    o4 = {B{1'bx}};
    o5 = {B{1'bx}};
    case (r0)
      0: o0 = i0;
      1: o1 = i0;
      2: o2 = i0;
      3: o3 = i0;
      4: o4 = i0;
      5: o5 = i0;
      default: ; // noop
    endcase
    case (r1)
      0: o0 = i1;
      1: o1 = i1;
      2: o2 = i1;
      3: o3 = i1;
      4: o4 = i1;
      5: o5 = i1;
      default: ; // noop
    endcase
    case (r2)
      0: o0 = i2;
      1: o1 = i2;
      2: o2 = i2;
      3: o3 = i2;
      4: o4 = i2;
      5: o5 = i2;
      default: ; // noop
    endcase
    case (r3)
      0: o0 = i3;
      1: o1 = i3;
      2: o2 = i3;
      3: o3 = i3;
      4: o4 = i3;
      5: o5 = i3;
      default: ; // noop
    endcase
    case (r4)
      0: o0 = i4;
      1: o1 = i4;
      2: o2 = i4;
      3: o3 = i4;
      4: o4 = i4;
      5: o5 = i4;
      default: ; // noop
    endcase
    case (r5)
      0: o0 = i5;
      1: o1 = i5;
      2: o2 = i5;
      3: o3 = i5;
      4: o4 = i5;
      5: o5 = i5;
      default: ; // noop
    endcase
  end
endmodule
