// minimal latency 3-sorter for B bits values
// generated by mlnsgenfast
// comparisons=3, total cases=8, orderings=6
module nsorter_3_fast #(
  parameter B = 64
) (
  input [B-1:0] i0,
  output reg [B-1:0] o0,
  input [B-1:0] i1,
  output reg [B-1:0] o1,
  input [B-1:0] i2,
  output reg [B-1:0] o2
);
  wire c0 = i0 < i1;
  wire c1 = i0 < i2;
  wire c2 = i1 < i2;
  always @(*) begin
    case ({c0,c1,c2})
      3'b111: begin o0=i0; o1=i1; o2=i2; end
      3'b110: begin o0=i0; o1=i2; o2=i1; end
      3'b011: begin o0=i1; o1=i0; o2=i2; end
      3'b001: begin o0=i1; o1=i2; o2=i0; end
      3'b100: begin o0=i2; o1=i0; o2=i1; end
      3'b000: begin o0=i2; o1=i1; o2=i0; end
      default: begin o0={B{1'bx}}; o1={B{1'bx}}; o2={B{1'bx}}; end // 2 invalid cases
    endcase
  end
endmodule
