// minimal latency 2-sorter for B bits values
// generated by mlnsgen
// comparisons=1, evals=3, total cases=2, valid cases=2, orderings=2
module nsorter_2 #(
  parameter B = 64
) (
  input [B-1:0] in [1:0],
  output [B-1:0] out [1:0]
);
  wire c0 = in[0] < in[1];
  always @(*) begin
    case ({c0})
      1'b0: out = {in[1],in[0]};
      1'b1: out = {in[0],in[1]};
    endcase
  end
endmodule
