C=ARGV[0].to_i
raise "illegal C=#{C}" if C < 2
SIGNED=false

n_comp=(C*C-C)/2
n_cases=2**n_comp
n_order=(1..C).reduce(1, :*)

puts "// minimal latency #{C}-sorter for B bits values"
puts "// generated by mlnsgenfastc"
puts "// comparisons=#{n_comp}, total cases=#{n_cases}, orderings=#{n_order}"
puts "module nsorter_#{C} #("
puts "  parameter B = 64"
puts ") ("
puts "  input signed_compare," if SIGNED
puts C.times.map {|x| ["  input [B-1:0] i#{x}", "  output reg [B-1:0] o#{x}"] }.flatten.join(",\n")
puts ");"
k=0
(0...C).each{|i|
	(i+1...C).each{|j|
		sc = "$signed(i#{i}) < $signed(i#{j})"
		uc = "i#{i} < i#{j}"
		puts "  wire c#{k} = " + (SIGNED ? "signed_compare ? (#{sc}) : (#{uc})" : uc) + ";"
		k += 1
	}
}

def merge_cases(s)
	loop {
		k = Set.new
		r = Set.new
		s.each_with_index{|a, i|
			next if k.include?(i)
			s.each_with_index{|b, j|
				next if j <= i || k.include?(j)
				p = nil
				b.length.times{|m|
					next if a[m] == b[m]
					if p != nil
						p = nil
						break
					end
					p = m
				}
				next if p == nil
				k << i << j
				n = a.dup
				n[p[0]] = '?'
				r << n
				break
			}
		}
		s.each_with_index{|a, i|
			r << a unless k.include?(i)
		}
		return r if r.length == s.length
		s = r.to_a
	}
end

r = Hash.new{|h,k| h[k] = Hash.new{|h,k| h[k] = [] } }
comparisons = (0...C).to_a.combination(2).to_a
(0...C).to_a.permutation.lazy.each do |perm|
	bit_str = comparisons.map { |i, j| perm.index(i) < perm.index(j) ? '1' : '0' }.join
	perm.each_with_index.each { |v, k| r[k][v] << bit_str }
end
r.sort.each{|o,v|
	puts "  always @(*) begin"
	puts "    casez ({#{(0...((C*C-C)/2)).to_a.map{|x| "c#{x}" }.join(",")}})"
	v.sort.each{|i,a|
		m = merge_cases(a)
		puts "      #{m.map{|x| "#{comparisons.length}'b#{x}" }.sort.join(',')}: o#{o}=i#{i}; // #{a.length} cases, #{m.length} merged cases"
	}
	puts "      default: o#{o}={B{1'bx}}; // #{n_cases-n_order} unreachable cases" unless n_cases==n_order
	puts "    endcase"
	puts "  end"
}

puts "endmodule"
