C=ARGV[0].to_i
raise "illegal C=#{C}" if C < 2

n_comp=(C*C-C)/2
n_cases=2**n_comp
n_order=(1..C).reduce(1, :*)

puts "// minimal latency #{C}-sorter for B bits values"
puts "// generated by mlnsgenfast"
puts "// comparisons=#{n_comp}, total cases=#{n_cases}, orderings=#{n_order}"
puts "module nsorter_#{C} #("
puts "  parameter B = 64"
puts ") ("
puts C.times.map {|x| ["  input [B-1:0] i#{x}", "  output reg [B-1:0] o#{x}"] }.flatten.join(",\n")
puts ");"
k=0
(0...C).each{|i|
	(i+1...C).each{|j|
		puts "  wire c#{k} = i#{i} < i#{j};"
		k += 1
	}
}
puts "  always @(*) begin"
puts "    case ({#{(0...((C*C-C)/2)).to_a.map{|x| "c#{x}" }.join(",")}})"

comparisons = (0...C).to_a.combination(2).to_a
(0...C).to_a.permutation.lazy.each do |perm|
	bit_str = comparisons.map { |i, j| perm.index(i) < perm.index(j) ? '1' : '0' }.join
	assignment = perm.each_with_index.map { |val, k| "o#{k}=i#{val}; " }.join
	puts "      #{bit_str.length}'b#{bit_str}: begin #{assignment}end"
end

puts "      default: begin #{C.times.map {|x| "o#{x}={B{1'bx}}; "}.join}end // #{n_cases-n_order} invalid cases" unless n_cases==n_order
puts "    endcase"
puts "  end"
puts "endmodule"
