C=ARGV[0].to_i
raise "illegal C=#{C}" if C < 2
SIGNED=false

n_comp=(C*C-C)/2
n_cases=2**n_comp
n_order=(1..C).reduce(1, :*)

puts "// minimal latency #{C}-sorter for B bits values"
puts "// generated by mlnsgenfastc2"
puts "// comparisons=#{n_comp}, total cases=#{n_cases}, orderings=#{n_order}"
puts "module nsorter_#{C} #("
puts "  parameter B = 64"
puts ") ("
puts "  input signed_compare," if SIGNED
puts C.times.map {|x| ["  input [B-1:0] i#{x}", "  output reg [B-1:0] o#{x}"] }.flatten.join(",\n")
puts ");"
c=[]
(0...C).each{|i|
	(i+1...C).each{|j|
		sc = "$signed(i#{i}) < $signed(i#{j})"
		uc = "i#{i} < i#{j}"
		puts "  wire c#{c.length} = " + (SIGNED ? "signed_compare ? (#{sc}) : (#{uc})" : uc) + ";"
		c << "c#{c.length}"
	}
}
puts "  wire [#{c.length-1}:0] c = {#{c.join(",")}};"

def merge_cases(s)
	s = Set.new(s)
	loop {
		modified = false
		s.each{|a|
			a.length.times{|i|
				b = nil
				if a[i] == "0"
					b = a.dup
					b[i] = "1"
				elsif a[i] == "1"
					b = a.dup
					b[i] = "0"
				else
					next
				end
				next unless s.include?(b)
				s.delete(a)
				s.delete(b)
				b[i] = "?"
				s << b
				modified = true
				a = b
			}
		}
		return s unless modified
	}
end

r = Hash.new{|h,k| h[k] = Hash.new{|h,k| h[k] = [] } }
comparisons = (0...C).to_a.combination(2).to_a
(0...C).to_a.permutation.lazy.each do |perm|
	bit_str = comparisons.map { |i, j| perm.index(i) < perm.index(j) ? '1' : '0' }.join
	perm.each_with_index.each { |v, k| r[k][v] << bit_str }
end
r.sort.each{|o,v|
	puts "  always @(*) begin"
	puts "    casez (c)"
	v.sort.each{|i,a|
		m = merge_cases(a)
		puts "      #{m.map{|x| "#{comparisons.length}'b#{x}" }.sort.join(', ')}: o#{o}=i#{i}; // #{a.length} cases, #{m.length} merged cases"
	}
	puts "      default: o#{o}={B{1'bx}}; // #{n_cases-n_order} unreachable cases" unless n_cases==n_order
	puts "    endcase"
	puts "  end"
}

puts "endmodule"
