C=ARGV[0].to_i
raise "illegal C=#{C}" if C < 2
SIGNED=false

n_comp=(C*C-C)/2
n_cases=2**n_comp
n_order=(1..C).reduce(1, :*)

puts "// minimal latency #{C}-sorter for B bits values"
puts "// generated by mlnsgenlarge"
puts "module nsorter_#{C}_large #("
puts "  parameter B = 64"
puts ") ("
puts "  input signed_compare," if SIGNED
puts C.times.map {|x| ["  input [B-1:0] i#{x}", "  output reg [B-1:0] o#{x}"] }.flatten.join(",\n")
puts ");"
(0...C).each{|i|
  acc = []
	(0...C).each{|j|
    next if i == j
    cmp = i < j ? ">" : ">="
		sc = "$signed(i#{i}) #{cmp} $signed(i#{j})"
		uc = "i#{i} #{cmp} i#{j}"
		acc << "(" + (SIGNED ? "signed_compare ? (#{sc}) : (#{uc})" : uc) + ")"
	}
  puts "  wire [#{(C-1).bit_length-1}:0] r#{i} = " + acc.join(" + ") +  + ";"
}
puts "  always @(*) begin"
C.times {|x| 
  puts "    o#{x} = {B{1'bx}};"
}
(0...C).each{|i|
  puts "    case (r#{i})"
  (0...C).each{|j|
    puts "      #{j}: o#{j} = i#{i};"
  }
  puts "      default: ; // noop" unless 2**((C-1).bit_length)==C
  puts "    endcase"
}
puts "  end"
puts "endmodule"

